[project]
name = "gpt-etl"
version = "0.1.0"
description = "ChatGPT ETL + RAG Playground"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.0.7",
    "embed-anything",
    "prefect>=3.3.7",
]
